name: fosha
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hive: 
  hive_flutter:
  get_it:
  bloc: null
  flutter_bloc: null
  http:
  animate_do: ^3.3.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  shimmer: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Mona-Sans
      fonts:
        - asset: assets/fonts/Mona-Sans-Regular.ttf
        - asset: assets/fonts/Mona-Sans-RegularItalic.ttf
          style: italic
    - family: Ceremonials
      fonts:
        - asset: assets/fonts/Ceremonials.ttf
       
          
    